---

- name: install > Packages
  apt:
    name: "{{ manala_elasticsearch_install_packages|default(manala_elasticsearch_install_packages_default, True) }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600

- block:
    - name: install > Version
      shell: dpkg -s elasticsearch
      register: __manala_elasticsearch_version
      changed_when: false
    - name: install > Version
      set_fact:
        manala_elasticsearch_version: "{{ __manala_elasticsearch_version.stdout | regex_search('Version: (1\\.\\d|\\d)', '\\1') | first }}"
      changed_when: false
  when: manala_elasticsearch_version is none
  check_mode: false
